<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SmartMed.UI</RootNamespace>
    <AssemblyName>SmartMed</AssemblyName>
    <StartupObject>SmartMed.UI.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartMed.Business\SmartMed.Business.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AdminShellForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="AdminShellForm.Designer.cs">
      <DependentUpon>AdminShellForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="AdminShellForm.resx">
      <DependentUpon>AdminShellForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="ManageCustomersForm.cs" />
    <Compile Update="ManageCustomersForm.Designer.cs">
      <DependentUpon>ManageCustomersForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="ManageCustomersForm.resx">
      <DependentUpon>ManageCustomersForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="ManageMedicinesForm.cs" />
    <Compile Update="ManageMedicinesForm.Designer.cs">
      <DependentUpon>ManageMedicinesForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="ManageMedicinesForm.resx">
      <DependentUpon>ManageMedicinesForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="ManageOrdersForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="ManageOrdersForm.Designer.cs">
      <DependentUpon>ManageOrdersForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="ManageOrdersForm.resx">
      <DependentUpon>ManageOrdersForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="AdminDashboardForm.cs" />
    <Compile Update="AdminDashboardForm.Designer.cs">
      <DependentUpon>AdminDashboardForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
