<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SmartMed</RootNamespace>
    <AssemblyName>SmartMed</AssemblyName>
    <StartupObject>SmartMed.UI.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="1.50.5147" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>
  <Target Name="StopRunningSmartMed" BeforeTargets="Build">
    <Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -Command &quot;Get-Process -Name SmartMed -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue&quot;" IgnoreExitCode="true" />
  </Target>
  <ItemGroup>
    <None Include="Assets\Fonts\HankenGrotesk-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\Fonts\HankenGrotesk-SemiBold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\Fonts\HankenGrotesk-Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Assets\Fonts\HankenGrotesk-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\HankenGrotesk-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\HankenGrotesk-Bold.ttf" />
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Forms\LoginForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\LoginForm.Designer.cs">
      <DependentUpon>LoginForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\LoginForm.resx">
      <DependentUpon>LoginForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\RegistrationForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\RegistrationForm.Designer.cs">
      <DependentUpon>RegistrationForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\RegistrationForm.resx">
      <DependentUpon>RegistrationForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Admin\AdminHostForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Admin\AdminHostForm.Designer.cs">
      <DependentUpon>AdminHostForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Admin\AdminHostForm.resx">
      <DependentUpon>AdminHostForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Admin\AdminDashboardForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Admin\AdminDashboardForm.Designer.cs">
      <DependentUpon>AdminDashboardForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Admin\AdminDashboardForm.resx">
      <DependentUpon>AdminDashboardForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Admin\ManageOrdersForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Admin\ManageOrdersForm.Designer.cs">
      <DependentUpon>ManageOrdersForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Admin\ManageOrdersForm.resx">
      <DependentUpon>ManageOrdersForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Admin\ManageCustomersForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Admin\ManageCustomersForm.Designer.cs">
      <DependentUpon>ManageCustomersForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Admin\ManageCustomersForm.resx">
      <DependentUpon>ManageCustomersForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Admin\ManageMedicinesForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Admin\ManageMedicinesForm.Designer.cs">
      <DependentUpon>ManageMedicinesForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Admin\ManageMedicinesForm.resx">
      <DependentUpon>ManageMedicinesForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Admin\ReportsForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Admin\ReportsForm.Designer.cs">
      <DependentUpon>ReportsForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Admin\ReportsForm.resx">
      <DependentUpon>ReportsForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Admin\AdminPageControl.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\CustomerPageControl.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\CustomerNavItem.cs" />
    <Compile Update="Forms\Customer\CustomerHostForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\CustomerHostForm.Designer.cs">
      <DependentUpon>CustomerHostForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Customer\CustomerHostForm.resx">
      <DependentUpon>CustomerHostForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Customer\CustomerDashboardForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\CustomerDashboardForm.Designer.cs">
      <DependentUpon>CustomerDashboardForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Customer\CustomerDashboardForm.resx">
      <DependentUpon>CustomerDashboardForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Customer\SearchMedicinesForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\SearchMedicinesForm.Designer.cs">
      <DependentUpon>SearchMedicinesForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Customer\SearchMedicinesForm.resx">
      <DependentUpon>SearchMedicinesForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Customer\PlaceOrderForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\PlaceOrderForm.Designer.cs">
      <DependentUpon>PlaceOrderForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Customer\PlaceOrderForm.resx">
      <DependentUpon>PlaceOrderForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Customer\TrackOrdersForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\TrackOrdersForm.Designer.cs">
      <DependentUpon>TrackOrdersForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Customer\TrackOrdersForm.resx">
      <DependentUpon>TrackOrdersForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Forms\Customer\ProfileManagementForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Customer\ProfileManagementForm.Designer.cs">
      <DependentUpon>ProfileManagementForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Forms\Customer\ProfileManagementForm.resx">
      <DependentUpon>ProfileManagementForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>
